packages:
  - 'apps/*'
  - 'libs/*'
autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  nx: true
  sharp: true
  unrs-resolver: false
  '@nestjs/core': false
  esbuild: set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
  bcrypt: set this to true or false
